UPDATE kirtan_tracks SET artist_slug='various';
UPDATE kirtan_tracks SET artist_slug='vishnujana-svami-maharaj-i-shrila-prabhupada' WHERE artist_slug='various' AND instr(title, 'Вишнуджана Свами Махарадж и Шрила Прабхупада')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-svarupa-damodara-gosvami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Сварупа Дамодара Госвами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='akinchana-krishna-das-babaji-maharaj' WHERE artist_slug='various' AND instr(title, 'Акинчана Кришна Дас Бабаджи Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-bringa-govinda-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Бринга Говинда Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-vigyana-gosvami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Вигьяна Госвами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='ananda-vardhana-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Ананда Вардхана Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-vaybhava-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Вайбхава Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='gopal-krishna-gosvami-maharaj' WHERE artist_slug='various' AND instr(title, 'Гопал Кришна Госвами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='kadamba-kanana-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Кадамба Канана Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='tamal-krishna-gosvami-maharaj' WHERE artist_slug='various' AND instr(title, 'Тамал Кришна Госвами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-tirtha-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Тиртха Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='gour-govinda-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Гоур Говинда Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='bhakti-charu-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Бхакти Чару Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='indradyumna-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Индрадьюмна Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='shachinandana-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Шачинандана Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='prabhavishnu-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Прабхавишну Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='vishnujana-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Вишнуджана Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='jayapataka-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Джаяпатака Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='niranjana-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Ниранджана Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='radhanatha-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Радханатха Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='chaytanya-chandra-charan-das' WHERE artist_slug='various' AND instr(title, 'Чайтанья Чандра Чаран Дас')=1;
UPDATE kirtan_tracks SET artist_slug='devamrita-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Девамрита Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='chandra-shekhar-acharya-das' WHERE artist_slug='various' AND instr(title, 'Чандра Шекхар Ачарья Дас')=1;
UPDATE kirtan_tracks SET artist_slug='shyamananda-kirtan-mandali' WHERE artist_slug='various' AND instr(title, 'Шямананда Киртан Мандали')=1;
UPDATE kirtan_tracks SET artist_slug='shivarama-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Шиварама Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='lokanath-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Локанатх Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='purnachandra-das-gosvami' WHERE artist_slug='various' AND instr(title, 'Пурначандра Дас Госвами')=1;
UPDATE kirtan_tracks SET artist_slug='akinchana-krishna-prabhu' WHERE artist_slug='various' AND instr(title, 'Акинчана Кришна Прабху')=1;
UPDATE kirtan_tracks SET artist_slug='seva-radhika-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Сева Радхика Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='suhotra-svami-maharaj' WHERE artist_slug='various' AND instr(title, 'Сухотра Свами Махарадж')=1;
UPDATE kirtan_tracks SET artist_slug='achyuta-gopi-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Ачьюта Гопи Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='premanjali-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Преманджали Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='raghunath-das-gosvami' WHERE artist_slug='various' AND instr(title, 'Рагхунатх Дас Госвами')=1;
UPDATE kirtan_tracks SET artist_slug='vrajendra-kumar-das' WHERE artist_slug='various' AND instr(title, 'Враджендра Кумар Дас')=1;
UPDATE kirtan_tracks SET artist_slug='sundarangi-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Сундаранги Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='madhurika-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Мадхурика Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='nama-sankirtana-das' WHERE artist_slug='various' AND instr(title, 'Нама Санкиртана Дас')=1;
UPDATE kirtan_tracks SET artist_slug='sundara-govinda-das' WHERE artist_slug='various' AND instr(title, 'Сундара Говинда Дас')=1;
UPDATE kirtan_tracks SET artist_slug='chaytanya-nitay-das' WHERE artist_slug='various' AND instr(title, 'Чайтанья Нитай Дас')=1;
UPDATE kirtan_tracks SET artist_slug='thakur-haridas-das' WHERE artist_slug='various' AND instr(title, 'Тхакур Харидас Дас')=1;
UPDATE kirtan_tracks SET artist_slug='gaurangi-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Гауранги Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='dhira-gauranga-das' WHERE artist_slug='various' AND instr(title, 'Дхира Гауранга Дас')=1;
UPDATE kirtan_tracks SET artist_slug='jahnavi-harrison' WHERE artist_slug='various' AND instr(title, 'Джахнави Харрисон')=1;
UPDATE kirtan_tracks SET artist_slug='amala-harinam-das' WHERE artist_slug='various' AND instr(title, 'Амала Харинам Дас')=1;
UPDATE kirtan_tracks SET artist_slug='chakrini-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Чакрини Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='madhuri-pura-dasa' WHERE artist_slug='various' AND instr(title, 'Мадхури Пура Даса')=1;
UPDATE kirtan_tracks SET artist_slug='krishna-tarana-das' WHERE artist_slug='various' AND instr(title, 'Кришна Тарана Дас')=1;
UPDATE kirtan_tracks SET artist_slug='radha-govinda-das' WHERE artist_slug='various' AND instr(title, 'Радха Говинда Дас')=1;
UPDATE kirtan_tracks SET artist_slug='achyuta-priya-das' WHERE artist_slug='various' AND instr(title, 'Ачьюта Прийа Дас')=1;
UPDATE kirtan_tracks SET artist_slug='bada-haridas-das' WHERE artist_slug='various' AND instr(title, 'Бада Харидас Дас')=1;
UPDATE kirtan_tracks SET artist_slug='ananga-kishor-das' WHERE artist_slug='various' AND instr(title, 'Ананга Кишор Дас')=1;
UPDATE kirtan_tracks SET artist_slug='kirtan-premi-das' WHERE artist_slug='various' AND instr(title, 'Киртан Преми Дас')=1;
UPDATE kirtan_tracks SET artist_slug='kishori-mohan-das' WHERE artist_slug='various' AND instr(title, 'Кишори Мохан Дас')=1;
UPDATE kirtan_tracks SET artist_slug='vraja-gopal-das' WHERE artist_slug='various' AND instr(title, 'Враджа Гопал Дас')=1;
UPDATE kirtan_tracks SET artist_slug='shrila-prabhupada' WHERE artist_slug='various' AND instr(title, 'Шрила Прабхупада')=1;
UPDATE kirtan_tracks SET artist_slug='nityananda-bend' WHERE artist_slug='various' AND instr(title, 'Нитьянанда Бэнд')=1;
UPDATE kirtan_tracks SET artist_slug='vishvambhara-das' WHERE artist_slug='various' AND instr(title, 'Вишвамбхара Дас')=1;
UPDATE kirtan_tracks SET artist_slug='rati-shekhar-das' WHERE artist_slug='various' AND instr(title, 'Рати Шекхар Дас')=1;
UPDATE kirtan_tracks SET artist_slug='yamuna-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Ямуна Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='nadiya-devi-dasi' WHERE artist_slug='various' AND instr(title, 'Надия Деви Даси')=1;
UPDATE kirtan_tracks SET artist_slug='dina-bandhu-das' WHERE artist_slug='various' AND instr(title, 'Дина Бандху Дас')=1;
UPDATE kirtan_tracks SET artist_slug='veda-vyasa-das' WHERE artist_slug='various' AND instr(title, 'Веда Вьяса Дас')=1;
UPDATE kirtan_tracks SET artist_slug='janardana-das' WHERE artist_slug='various' AND instr(title, 'Джанардана Дас')=1;
UPDATE kirtan_tracks SET artist_slug='prapannam-das' WHERE artist_slug='various' AND instr(title, 'Прапаннам Дас')=1;
UPDATE kirtan_tracks SET artist_slug='shachi-suta-das' WHERE artist_slug='various' AND instr(title, 'Шачи Сута Дас')=1;
UPDATE kirtan_tracks SET artist_slug='shishtakrit-das' WHERE artist_slug='various' AND instr(title, 'Шиштакрит Дас')=1;
UPDATE kirtan_tracks SET artist_slug='adi-rasa-das' WHERE artist_slug='various' AND instr(title, 'Ади Раса Дас')=1;
UPDATE kirtan_tracks SET artist_slug='sarvatma-das' WHERE artist_slug='various' AND instr(title, 'Сарватма Дас')=1;
UPDATE kirtan_tracks SET artist_slug='sulochana-das' WHERE artist_slug='various' AND instr(title, 'Сулочана Дас')=1;
UPDATE kirtan_tracks SET artist_slug='vatsala-das' WHERE artist_slug='various' AND instr(title, 'Ватсала Дас')=1;
UPDATE kirtan_tracks SET artist_slug='madhava-das' WHERE artist_slug='various' AND instr(title, 'Мадхава Дас')=1;
UPDATE kirtan_tracks SET artist_slug='ojasvi-das' WHERE artist_slug='various' AND instr(title, 'Оджасви Дас')=1;
UPDATE kirtan_tracks SET artist_slug='yadubara-das' WHERE artist_slug='various' AND instr(title, 'Ядубара Дас')=1;
UPDATE kirtan_tracks SET artist_slug='mukunda-das' WHERE artist_slug='various' AND instr(title, 'Мукунда Дас')=1;
UPDATE kirtan_tracks SET artist_slug='aindra-das' WHERE artist_slug='various' AND instr(title, 'Аиндра Дас')=1;
UPDATE kirtan_tracks SET artist_slug='akshara-das' WHERE artist_slug='various' AND instr(title, 'Акшара Дас')=1;
UPDATE kirtan_tracks SET artist_slug='gaura-vani' WHERE artist_slug='various' AND instr(title, 'Гаура Вани')=1;
UPDATE kirtan_tracks SET artist_slug='pavana-das' WHERE artist_slug='various' AND instr(title, 'Павана Дас')=1;
UPDATE kirtan_tracks SET artist_slug='gadai-giri' WHERE artist_slug='various' AND instr(title, 'Гадаи Гири')=1;
UPDATE kirtan_tracks SET artist_slug='bitu-malik' WHERE artist_slug='various' AND instr(title, 'Биту Малик')=1;
UPDATE kirtan_tracks SET artist_slug='havi-das' WHERE artist_slug='various' AND instr(title, 'Хави Дас')=1;
UPDATE kirtan_artists SET sort=0 WHERE slug='shrila-prabhupada';
UPDATE kirtan_artists SET sort=10 WHERE slug='adi-rasa-das';
UPDATE kirtan_artists SET sort=20 WHERE slug='aindra-das';
UPDATE kirtan_artists SET sort=30 WHERE slug='akinchana-krishna-das-babaji-maharaj';
UPDATE kirtan_artists SET sort=40 WHERE slug='akinchana-krishna-prabhu';
UPDATE kirtan_artists SET sort=50 WHERE slug='akshara-das';
UPDATE kirtan_artists SET sort=60 WHERE slug='amala-harinam-das';
UPDATE kirtan_artists SET sort=70 WHERE slug='ananga-kishor-das';
UPDATE kirtan_artists SET sort=80 WHERE slug='ananda-vardhana-svami-maharaj';
UPDATE kirtan_artists SET sort=90 WHERE slug='achyuta-gopi-devi-dasi';
UPDATE kirtan_artists SET sort=100 WHERE slug='achyuta-priya-das';
UPDATE kirtan_artists SET sort=110 WHERE slug='bada-haridas-das';
UPDATE kirtan_artists SET sort=120 WHERE slug='bitu-malik';
UPDATE kirtan_artists SET sort=130 WHERE slug='bhakti-bringa-govinda-svami-maharaj';
UPDATE kirtan_artists SET sort=140 WHERE slug='bhakti-vaybhava-svami-maharaj';
UPDATE kirtan_artists SET sort=150 WHERE slug='bhakti-vigyana-gosvami-maharaj';
UPDATE kirtan_artists SET sort=160 WHERE slug='bhakti-svarupa-damodara-gosvami-maharaj';
UPDATE kirtan_artists SET sort=170 WHERE slug='bhakti-tirtha-svami-maharaj';
UPDATE kirtan_artists SET sort=180 WHERE slug='bhakti-charu-svami-maharaj';
UPDATE kirtan_artists SET sort=190 WHERE slug='vatsala-das';
UPDATE kirtan_artists SET sort=200 WHERE slug='veda-vyasa-das';
UPDATE kirtan_artists SET sort=210 WHERE slug='vishvambhara-das';
UPDATE kirtan_artists SET sort=220 WHERE slug='vishnujana-svami-maharaj';
UPDATE kirtan_artists SET sort=230 WHERE slug='vishnujana-svami-maharaj-i-shrila-prabhupada';
UPDATE kirtan_artists SET sort=240 WHERE slug='vraja-gopal-das';
UPDATE kirtan_artists SET sort=250 WHERE slug='vrajendra-kumar-das';
UPDATE kirtan_artists SET sort=260 WHERE slug='gadai-giri';
UPDATE kirtan_artists SET sort=270 WHERE slug='gaura-vani';
UPDATE kirtan_artists SET sort=280 WHERE slug='gaurangi-devi-dasi';
UPDATE kirtan_artists SET sort=290 WHERE slug='gopal-krishna-gosvami-maharaj';
UPDATE kirtan_artists SET sort=300 WHERE slug='gour-govinda-svami-maharaj';
UPDATE kirtan_artists SET sort=310 WHERE slug='devamrita-svami-maharaj';
UPDATE kirtan_artists SET sort=320 WHERE slug='janardana-das';
UPDATE kirtan_artists SET sort=330 WHERE slug='jahnavi-harrison';
UPDATE kirtan_artists SET sort=340 WHERE slug='jayapataka-svami-maharaj';
UPDATE kirtan_artists SET sort=350 WHERE slug='dina-bandhu-das';
UPDATE kirtan_artists SET sort=360 WHERE slug='dhira-gauranga-das';
UPDATE kirtan_artists SET sort=370 WHERE slug='indradyumna-svami-maharaj';
UPDATE kirtan_artists SET sort=380 WHERE slug='kadamba-kanana-svami-maharaj';
UPDATE kirtan_artists SET sort=390 WHERE slug='kirtan-premi-das';
UPDATE kirtan_artists SET sort=400 WHERE slug='kishori-mohan-das';
UPDATE kirtan_artists SET sort=410 WHERE slug='krishna-tarana-das';
UPDATE kirtan_artists SET sort=420 WHERE slug='lokanath-svami-maharaj';
UPDATE kirtan_artists SET sort=430 WHERE slug='madhava-das';
UPDATE kirtan_artists SET sort=440 WHERE slug='madhuri-pura-dasa';
UPDATE kirtan_artists SET sort=450 WHERE slug='madhurika-devi-dasi';
UPDATE kirtan_artists SET sort=460 WHERE slug='mukunda-das';
UPDATE kirtan_artists SET sort=470 WHERE slug='nadiya-devi-dasi';
UPDATE kirtan_artists SET sort=480 WHERE slug='nama-sankirtana-das';
UPDATE kirtan_artists SET sort=490 WHERE slug='niranjana-svami-maharaj';
UPDATE kirtan_artists SET sort=500 WHERE slug='nityananda-bend';
UPDATE kirtan_artists SET sort=510 WHERE slug='ojasvi-das';
UPDATE kirtan_artists SET sort=520 WHERE slug='pavana-das';
UPDATE kirtan_artists SET sort=530 WHERE slug='prabhavishnu-svami-maharaj';
UPDATE kirtan_artists SET sort=540 WHERE slug='prapannam-das';
UPDATE kirtan_artists SET sort=550 WHERE slug='premanjali-devi-dasi';
UPDATE kirtan_artists SET sort=560 WHERE slug='purnachandra-das-gosvami';
UPDATE kirtan_artists SET sort=570 WHERE slug='raghunath-das-gosvami';
UPDATE kirtan_artists SET sort=580 WHERE slug='radha-govinda-das';
UPDATE kirtan_artists SET sort=590 WHERE slug='radhanatha-svami-maharaj';
UPDATE kirtan_artists SET sort=600 WHERE slug='rati-shekhar-das';
UPDATE kirtan_artists SET sort=610 WHERE slug='sarvatma-das';
UPDATE kirtan_artists SET sort=620 WHERE slug='seva-radhika-devi-dasi';
UPDATE kirtan_artists SET sort=630 WHERE slug='sulochana-das';
UPDATE kirtan_artists SET sort=640 WHERE slug='sundara-govinda-das';
UPDATE kirtan_artists SET sort=650 WHERE slug='sundarangi-devi-dasi';
UPDATE kirtan_artists SET sort=660 WHERE slug='suhotra-svami-maharaj';
UPDATE kirtan_artists SET sort=670 WHERE slug='tamal-krishna-gosvami-maharaj';
UPDATE kirtan_artists SET sort=680 WHERE slug='thakur-haridas-das';
UPDATE kirtan_artists SET sort=690 WHERE slug='havi-das';
UPDATE kirtan_artists SET sort=700 WHERE slug='chaytanya-nitay-das';
UPDATE kirtan_artists SET sort=710 WHERE slug='chaytanya-chandra-charan-das';
UPDATE kirtan_artists SET sort=720 WHERE slug='chakrini-devi-dasi';
UPDATE kirtan_artists SET sort=730 WHERE slug='chandra-shekhar-acharya-das';
UPDATE kirtan_artists SET sort=740 WHERE slug='shachi-suta-das';
UPDATE kirtan_artists SET sort=750 WHERE slug='shachinandana-svami-maharaj';
UPDATE kirtan_artists SET sort=760 WHERE slug='shivarama-svami-maharaj';
UPDATE kirtan_artists SET sort=770 WHERE slug='shishtakrit-das';
UPDATE kirtan_artists SET sort=780 WHERE slug='shyamananda-kirtan-mandali';
UPDATE kirtan_artists SET sort=790 WHERE slug='yadubara-das';
UPDATE kirtan_artists SET sort=800 WHERE slug='yamuna-devi-dasi';
UPDATE kirtan_artists SET sort=9999 WHERE slug='various';