UPDATE kirtan_tracks SET artist_slug='various';
UPDATE kirtan_tracks SET artist_slug='vishnujana-svami-maharaj-i-shrila-prabhupada' WHERE artist_slug='various' AND title LIKE 'Вишнуджана Свами Махарадж и Шрила Прабхупада%';
UPDATE kirtan_tracks SET artist_slug='bhakti-svarupa-damodara-gosvami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Сварупа Дамодара Госвами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='akinchana-krishna-das-babaji-maharaj' WHERE artist_slug='various' AND title LIKE 'Акинчана Кришна Дас Бабаджи Махарадж%';
UPDATE kirtan_tracks SET artist_slug='bhakti-bringa-govinda-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Бринга Говинда Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='bhakti-vigyana-gosvami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Вигьяна Госвами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='ananda-vardhana-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Ананда Вардхана Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='bhakti-vaybhava-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Вайбхава Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='gopal-krishna-gosvami-maharaj' WHERE artist_slug='various' AND title LIKE 'Гопал Кришна Госвами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='kadamba-kanana-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Кадамба Канана Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='tamal-krishna-gosvami-maharaj' WHERE artist_slug='various' AND title LIKE 'Тамал Кришна Госвами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='bhakti-tirtha-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Тиртха Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='gour-govinda-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Гоур Говинда Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='bhakti-charu-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Бхакти Чару Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='indradyumna-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Индрадьюмна Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='shachinandana-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Шачинандана Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='prabhavishnu-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Прабхавишну Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='vishnujana-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Вишнуджана Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='jayapataka-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Джаяпатака Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='niranjana-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Ниранджана Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='radhanatha-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Радханатха Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='chaytanya-chandra-charan-das' WHERE artist_slug='various' AND title LIKE 'Чайтанья Чандра Чаран Дас%';
UPDATE kirtan_tracks SET artist_slug='devamrita-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Девамрита Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='chandra-shekhar-acharya-das' WHERE artist_slug='various' AND title LIKE 'Чандра Шекхар Ачарья Дас%';
UPDATE kirtan_tracks SET artist_slug='shyamananda-kirtan-mandali' WHERE artist_slug='various' AND title LIKE 'Шямананда Киртан Мандали%';
UPDATE kirtan_tracks SET artist_slug='shivarama-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Шиварама Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='lokanath-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Локанатх Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='purnachandra-das-gosvami' WHERE artist_slug='various' AND title LIKE 'Пурначандра Дас Госвами%';
UPDATE kirtan_tracks SET artist_slug='akinchana-krishna-prabhu' WHERE artist_slug='various' AND title LIKE 'Акинчана Кришна Прабху%';
UPDATE kirtan_tracks SET artist_slug='seva-radhika-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Сева Радхика Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='suhotra-svami-maharaj' WHERE artist_slug='various' AND title LIKE 'Сухотра Свами Махарадж%';
UPDATE kirtan_tracks SET artist_slug='achyuta-gopi-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Ачьюта Гопи Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='premanjali-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Преманджали Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='raghunath-das-gosvami' WHERE artist_slug='various' AND title LIKE 'Рагхунатх Дас Госвами%';
UPDATE kirtan_tracks SET artist_slug='vrajendra-kumar-das' WHERE artist_slug='various' AND title LIKE 'Враджендра Кумар Дас%';
UPDATE kirtan_tracks SET artist_slug='sundarangi-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Сундаранги Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='madhurika-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Мадхурика Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='nama-sankirtana-das' WHERE artist_slug='various' AND title LIKE 'Нама Санкиртана Дас%';
UPDATE kirtan_tracks SET artist_slug='sundara-govinda-das' WHERE artist_slug='various' AND title LIKE 'Сундара Говинда Дас%';
UPDATE kirtan_tracks SET artist_slug='chaytanya-nitay-das' WHERE artist_slug='various' AND title LIKE 'Чайтанья Нитай Дас%';
UPDATE kirtan_tracks SET artist_slug='thakur-haridas-das' WHERE artist_slug='various' AND title LIKE 'Тхакур Харидас Дас%';
UPDATE kirtan_tracks SET artist_slug='gaurangi-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Гауранги Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='dhira-gauranga-das' WHERE artist_slug='various' AND title LIKE 'Дхира Гауранга Дас%';
UPDATE kirtan_tracks SET artist_slug='jahnavi-harrison' WHERE artist_slug='various' AND title LIKE 'Джахнави Харрисон%';
UPDATE kirtan_tracks SET artist_slug='amala-harinam-das' WHERE artist_slug='various' AND title LIKE 'Амала Харинам Дас%';
UPDATE kirtan_tracks SET artist_slug='chakrini-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Чакрини Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='madhuri-pura-dasa' WHERE artist_slug='various' AND title LIKE 'Мадхури Пура Даса%';
UPDATE kirtan_tracks SET artist_slug='krishna-tarana-das' WHERE artist_slug='various' AND title LIKE 'Кришна Тарана Дас%';
UPDATE kirtan_tracks SET artist_slug='radha-govinda-das' WHERE artist_slug='various' AND title LIKE 'Радха Говинда Дас%';
UPDATE kirtan_tracks SET artist_slug='achyuta-priya-das' WHERE artist_slug='various' AND title LIKE 'Ачьюта Прийа Дас%';
UPDATE kirtan_tracks SET artist_slug='bada-haridas-das' WHERE artist_slug='various' AND title LIKE 'Бада Харидас Дас%';
UPDATE kirtan_tracks SET artist_slug='ananga-kishor-das' WHERE artist_slug='various' AND title LIKE 'Ананга Кишор Дас%';
UPDATE kirtan_tracks SET artist_slug='kirtan-premi-das' WHERE artist_slug='various' AND title LIKE 'Киртан Преми Дас%';
UPDATE kirtan_tracks SET artist_slug='kishori-mohan-das' WHERE artist_slug='various' AND title LIKE 'Кишори Мохан Дас%';
UPDATE kirtan_tracks SET artist_slug='vraja-gopal-das' WHERE artist_slug='various' AND title LIKE 'Враджа Гопал Дас%';
UPDATE kirtan_tracks SET artist_slug='shrila-prabhupada' WHERE artist_slug='various' AND title LIKE 'Шрила Прабхупада%';
UPDATE kirtan_tracks SET artist_slug='nityananda-bend' WHERE artist_slug='various' AND title LIKE 'Нитьянанда Бэнд%';
UPDATE kirtan_tracks SET artist_slug='vishvambhara-das' WHERE artist_slug='various' AND title LIKE 'Вишвамбхара Дас%';
UPDATE kirtan_tracks SET artist_slug='rati-shekhar-das' WHERE artist_slug='various' AND title LIKE 'Рати Шекхар Дас%';
UPDATE kirtan_tracks SET artist_slug='yamuna-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Ямуна Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='nadiya-devi-dasi' WHERE artist_slug='various' AND title LIKE 'Надия Деви Даси%';
UPDATE kirtan_tracks SET artist_slug='dina-bandhu-das' WHERE artist_slug='various' AND title LIKE 'Дина Бандху Дас%';
UPDATE kirtan_tracks SET artist_slug='veda-vyasa-das' WHERE artist_slug='various' AND title LIKE 'Веда Вьяса Дас%';
UPDATE kirtan_tracks SET artist_slug='janardana-das' WHERE artist_slug='various' AND title LIKE 'Джанардана Дас%';
UPDATE kirtan_tracks SET artist_slug='prapannam-das' WHERE artist_slug='various' AND title LIKE 'Прапаннам Дас%';
UPDATE kirtan_tracks SET artist_slug='shachi-suta-das' WHERE artist_slug='various' AND title LIKE 'Шачи Сута Дас%';
UPDATE kirtan_tracks SET artist_slug='shishtakrit-das' WHERE artist_slug='various' AND title LIKE 'Шиштакрит Дас%';
UPDATE kirtan_tracks SET artist_slug='adi-rasa-das' WHERE artist_slug='various' AND title LIKE 'Ади Раса Дас%';
UPDATE kirtan_tracks SET artist_slug='sarvatma-das' WHERE artist_slug='various' AND title LIKE 'Сарватма Дас%';
UPDATE kirtan_tracks SET artist_slug='sulochana-das' WHERE artist_slug='various' AND title LIKE 'Сулочана Дас%';
UPDATE kirtan_tracks SET artist_slug='vatsala-das' WHERE artist_slug='various' AND title LIKE 'Ватсала Дас%';
UPDATE kirtan_tracks SET artist_slug='madhava-das' WHERE artist_slug='various' AND title LIKE 'Мадхава Дас%';
UPDATE kirtan_tracks SET artist_slug='ojasvi-das' WHERE artist_slug='various' AND title LIKE 'Оджасви Дас%';
UPDATE kirtan_tracks SET artist_slug='yadubara-das' WHERE artist_slug='various' AND title LIKE 'Ядубара Дас%';
UPDATE kirtan_tracks SET artist_slug='mukunda-das' WHERE artist_slug='various' AND title LIKE 'Мукунда Дас%';
UPDATE kirtan_tracks SET artist_slug='aindra-das' WHERE artist_slug='various' AND title LIKE 'Аиндра Дас%';
UPDATE kirtan_tracks SET artist_slug='akshara-das' WHERE artist_slug='various' AND title LIKE 'Акшара Дас%';
UPDATE kirtan_tracks SET artist_slug='gaura-vani' WHERE artist_slug='various' AND title LIKE 'Гаура Вани%';
UPDATE kirtan_tracks SET artist_slug='pavana-das' WHERE artist_slug='various' AND title LIKE 'Павана Дас%';
UPDATE kirtan_tracks SET artist_slug='gadai-giri' WHERE artist_slug='various' AND title LIKE 'Гадаи Гири%';
UPDATE kirtan_tracks SET artist_slug='bitu-malik' WHERE artist_slug='various' AND title LIKE 'Биту Малик%';
UPDATE kirtan_tracks SET artist_slug='havi-das' WHERE artist_slug='various' AND title LIKE 'Хави Дас%';