-- 0011_book_catalog.sql — каталог библиотеки в D1 + связь автор→личность (FK на entities).
-- Источник: apps/web/src/books.ts (LIBRARY). Закрывает дрейф схемы (см. docs/PASSPORT.md §B).
DROP TABLE IF EXISTS book_catalog;
CREATE TABLE book_catalog (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  iast TEXT,
  note TEXT,
  author_name TEXT,
  author_entity_id TEXT REFERENCES entities(id),
  lineage TEXT NOT NULL CHECK (lineage IN ('prabhupada','acharya','guru-iskcon')),
  readable INTEGER NOT NULL DEFAULT 0,
  audio INTEGER NOT NULL DEFAULT 0,
  also TEXT,
  sort INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_book_catalog_lineage ON book_catalog(lineage, sort);
CREATE INDEX idx_book_catalog_author ON book_catalog(author_entity_id);
INSERT INTO book_catalog (id,title,iast,note,author_name,author_entity_id,lineage,readable,audio,also,sort) VALUES
('bg','Бхагавад-гита как она есть','Bhagavad-gītā','Песнь Бога','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Gita Гитопанишад Bhagavadgita Prabhupada Bhaktivedanta',0),
('sb','Шримад-Бхагаватам','Śrīmad-Bhāgavatam','Зрелый плод древа Вед','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Вьясадева Vyasa Бхагавата-пурана Bhagavata Purana Srimad Prabhupada Bhaktivedanta',1),
('cc','Шри Чайтанья-чаритамрита','Śrī Caitanya-caritāmṛta','Деяния Гауранга Махапрабху','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Кришнадас Кавираджа Krishnadasa Kaviraja Chaitanya Caitanya Prabhupada Bhaktivedanta',2),
('brs','Нектар преданности','Bhakti-rasāmṛta-sindhu','Наука преданного служения','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Рупа Госвами Rupa Goswami Gosvami Bhakti-rasamrita Prabhupada Bhaktivedanta',3),
('krishna-book','Кришна. Верховная Личность Бога','Kṛṣṇa','Игры Кришны из Десятой песни','Шрила Прабхупада','prabhupada','prabhupada',0,0,'Krishna Кришна KRSNA Prabhupada Bhaktivedanta',4),
('tlc','Учение Шри Чайтаньи','Teachings of Lord Caitanya',NULL,'Шрила Прабхупада','prabhupada','prabhupada',0,0,'Teachings Chaitanya Caitanya Учение Prabhupada Bhaktivedanta',5),
('noi','Нектар наставлений','Upadeśāmṛta','Наставления Шрилы Рупы Госвами','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Рупа Госвами Rupa Goswami Upadeshamrita Upadesamrta Nectar of Instruction Prabhupada Bhaktivedanta',6),
('iso','Шри Ишопанишад','Śrī Īśopaniṣad','Мантры совершенного знания','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Isopanishad Ishopanishad Ишопанишада Iso Prabhupada Bhaktivedanta',7),
('owk','На пути к Кришне','On the Way to Kṛṣṇa',NULL,'Шрила Прабхупада','prabhupada','prabhupada',1,0,'On the Way to Krishna Путь Прабхупада Bhaktivedanta',8),
('rv','Раджа-видья. Царь знания','Rāja-vidyā','Царь знания','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Raja-vidya King of Knowledge Раджа-видья Прабхупада Bhaktivedanta',9),
('pop','Путь к совершенству','The Path of Perfection','Йога по «Бхагавад-гите»','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Path of Perfection Путь к совершенству Прабхупада Bhaktivedanta',10),
('bbd','По ту сторону рождения и смерти','Beyond Birth and Death',NULL,'Шрила Прабхупада','prabhupada','prabhupada',1,0,'Beyond Birth and Death По ту сторону Прабхупада Bhaktivedanta',11),
('poy','Совершенство йоги','The Perfection of Yoga',NULL,'Шрила Прабхупада','prabhupada','prabhupada',1,0,'Perfection of Yoga Совершенство йоги Прабхупада Bhaktivedanta',12),
('sc','Ещё один шанс','A Second Chance','История Аджамилы','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Second Chance Ещё один шанс Аджамила Ajamila Прабхупада Bhaktivedanta',13),
('tqk','Молитвы царицы Кунти','Teachings of Queen Kuntī','Молитвы из «Бхагаватам»','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Teachings of Queen Kunti Молитвы царицы Кунти Kuntidevi Прабхупада Bhaktivedanta',14),
('lob','Свет Бхагаваты','Light of the Bhāgavata','48 медитаций','Шрила Прабхупада','prabhupada','prabhupada',1,0,'Light of the Bhagavata Свет Бхагаваты Прабхупада Bhaktivedanta',15),
('spl','Шрила Прабхупада-лиламрита','Śrīla Prabhupāda-līlāmṛta','Жизнеописание Ачарьи-основателя','Сатсварупа Дас Госвами','satsvarupa-das-goswami','prabhupada',1,1,'Prabhupada-lilamrita Лиламрита Satsvarupa Прабхупада',16),
('cb','Чайтанья-бхагавата','Caitanya-bhāgavata',NULL,'Вриндаван дас Тхакур','vrindavana-dasa-thakura','acharya',0,0,'Чайтанья-бхагавата Caitanya-bhagavata Вриндаван',17),
('cm','Чайтанья-мангала','Caitanya-maṅgala',NULL,'Лочана дас Тхакур','lochana-dasa-thakura','acharya',0,0,'Чайтанья-мангала Caitanya-mangala Лочана',18),
('ggd','Гаура-ганоддеша-дипика','Gaura-gaṇoddeśa-dīpikā',NULL,'Кави Карнапура','kavi-karnapura','acharya',0,0,'Гаура-ганоддеша Gaura-ganoddesa Карнапура',19),
('bs','Брахма-самхита','Brahma-saṁhitā','Молитвы Господа Брахмы','Господь Брахма','brahma','acharya',1,1,'Brahma Brahmasamhita Брахма-самхита Говинда сат-чид-ананда',20),
('vp','Вишну-пурана','Viṣṇu-purāṇa','Пурана о Господе Вишну','Парашара Муни',NULL,'acharya',1,0,'Vishnu Purana Вишну-пурана Парашара хладини сандхини самвит бхага',21),
('hbv','Хари-бхакти-виласа','Hari-bhakti-vilāsa','Свод вайшнавской практики',NULL,NULL,'acharya',0,0,'Sanatana',22),
('vedanta-sutra','Веданта-сутра','Vedānta-sūtra',NULL,'Вьясадева','vyasadeva','acharya',0,0,'Vyasa Vyasadeva Baladeva Vedanta',23),
('mahabharata','Махабхарата','Mahābhārata',NULL,'Вьясадева','vyasadeva','acharya',0,0,'Vyasa Vyasadeva',24),
('puranas','Пураны','Purāṇa',NULL,'Вьясадева','vyasadeva','acharya',0,0,'Vyasa Vyasadeva Purana',25),
('ramayana','Рамаяна','Rāmāyaṇa',NULL,'Валмики','valmiki','acharya',0,0,'Valmiki',26),
('upanishads','Упанишады','Upaniṣad','Философская вершина Вед',NULL,NULL,'acharya',0,0,'Upanishad',27),
('vedas','Веды','Veda','Изначальное ведическое знание',NULL,NULL,'acharya',0,0,'Veda',28),
('prabhupada-lilamrita','Шрила Прабхупада-лиламрита','Śrīla Prabhupāda-līlāmṛta','Жизнеописание Ачарьи-основателя','Сатсварупа Дас Госвами','satsvarupa-das-goswami','guru-iskcon',0,0,'Prabhupada Bhaktivedanta Satsvarupa Lilamrita',29),
('ujjvala-nilamani','Уджжвала-ниламани','Ujjvala-nīlamaṇi','Наука о супружеской расе (мадхурья) и её разновидностях.','Рупа Госвами','rupa-goswami','acharya',0,0,'Ujjvala Рупа madhurya Уджжвала-ниламани',30),
('radha-krishna-ganoddesa-dipika','Радха-Кришна-ганоддеша-дипика','Rādhā-Kṛṣṇa-gaṇoddeśa-dīpikā','Описание вечных спутников Радхи и Кришны во Врадже.','Рупа Госвами','rupa-goswami','acharya',0,0,'ганоддеша Рупа спутники Радха-Кришна-ганоддеша-дипика',31),
('vidagdha-madhava','Видагдха-Мадхава','Vidagdha-mādhava','Драма об играх Кришны во Вриндаване.','Рупа Госвами','rupa-goswami','acharya',0,0,'Vidagdha драма Рупа Видагдха-Мадхава',32),
('lalita-madhava','Лалита-Мадхава','Lalita-mādhava','Драма об играх Кришны в Матхуре и Двараке.','Рупа Госвами','rupa-goswami','acharya',0,0,'Lalita драма Рупа Лалита-Мадхава',33),
('stava-mala','Става-мала','Stava-mālā','Собрание молитв и гимнов Рупы Госвами.','Рупа Госвами','rupa-goswami','acharya',0,0,'Stava молитвы Рупа Става-мала',34),
('padyavali','Падьявали','Padyāvalī','Антология преданных стихов вайшнавских поэтов.','Рупа Госвами','rupa-goswami','acharya',0,0,'Padyavali антология Падьявали',35),
('hamsaduta','Хамсадута','Haṁsadūta','Поэма-послание: гопи шлют лебедя вестником к Кришне.','Рупа Госвами','rupa-goswami','acharya',0,0,'Hamsaduta лебедь Хамсадута',36),
('uddhava-sandesha','Уддхава-сандеша','Uddhava-sandeśa','Поэма о послании, переданном через Уддхаву во Врадж.','Рупа Госвами','rupa-goswami','acharya',0,0,'Uddhava послание Уддхава-сандеша',37),
('dana-keli-kaumudi','Дана-кели-каумуди','Dāna-keli-kaumudī','Драма об игре сбора пошлины (дана-лила) у Говардхана.','Рупа Госвами','rupa-goswami','acharya',0,0,'dana keli Рупа Дана-кели-каумуди',38),
('mathura-mahatmya','Матхура-махатмья','Mathurā-māhātmya','Свод свидетельств писаний о славе Матхура-мандалы.','Рупа Госвами','rupa-goswami','acharya',0,0,'Mathura махатмья Матхура-махатмья',39),
('brihad-bhagavatamrita','Брихад-Бхагаватамрита','Bṛhad-bhāgavatāmṛta','Поиск высшего получателя милости и высшей обители; путь Гопа-кумара.','Санатана Госвами','sanatana-goswami','acharya',0,0,'Brihad Санатана Брихад-Бхагаватамрита',40),
('dashama-tippani','Дашама-типпани (Вайшнава-тошани)','Daśama-ṭippanī','Комментарий к Десятой песни «Шримад-Бхагаватам».','Санатана Госвами','sanatana-goswami','acharya',0,0,'toshani Санатана комментарий Дашама-типпани (Вайшнава-тошани)',41),
('shat-sandarbha','Шат-сандарбха','Ṣaṭ-sandarbha','Шесть философских трактатов — систематика гаудия-веданты.','Джива Госвами','jiva-goswami','acharya',0,0,'sandarbha Джива Tattva Bhagavat Шат-сандарбха',42),
('ks','Кришна-сандарбха','Kṛṣṇa-sandarbha','Трактат, устанавливающий, что Кришна — Сваям Бхагаван (4-я из Сандарбх).','Джива Госвами','jiva-goswami','acharya',1,0,'sandarbha Джива Кришна-сандарбха krishna-sandarbha Сваям Бхагаван',43),
('gopala-champu','Гопала-чампу','Gopāla-campū','Поэтико-прозаический свод вечных игр Кришны во Врадже.','Джива Госвами','jiva-goswami','acharya',0,0,'champu Джива Гопала-чампу',44),
('hari-namamrita-vyakarana','Хари-намамрита-вьякарана','Hari-nāmāmṛta-vyākaraṇa','Санскритская грамматика, построенная на именах Господа.','Джива Госвами','jiva-goswami','acharya',0,0,'грамматика vyakarana Джива Хари-намамрита-вьякарана',45),
('sarva-samvadini','Сарва-самвадини','Sarva-saṁvādinī','Авторский комментарий-дополнение к «Сандарбхам».','Джива Госвами','jiva-goswami','acharya',0,0,'samvadini Джива Сарва-самвадини',46),
('stavavali','Стававали','Stavāvalī','Собрание молитв в настроении служанок Радхи.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'Stavavali молитвы Рагхунатха Стававали',47),
('manah-shiksha','Манах-шикша','Manaḥ-śikṣā','Одиннадцать стихов наставления собственному уму.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'manah наставление уму Манах-шикша',48),
('mukta-charita','Мукта-чарита','Muktā-carita','Поэма об игре с жемчугом Радхи и Кришны.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'mukta жемчуг Мукта-чарита',49),
('vraja-vilasa-stava','Враджа-виласа-става','Vraja-vilāsa-stava','Молитвы, прославляющие игры и места Враджа.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'vraja vilasa Враджа-виласа-става',50),
('sat-kriya-sara-dipika','Сат-крия-сара-дипика','Sat-kriyā-sāra-dīpikā','Руководство по вайшнавским обрядам и самскарам.','Гопал Бхатта Госвами','gopala-bhatta-goswami','acharya',0,0,'kriya обряды Гопал Сат-крия-сара-дипика',51),
('ananda-vrindavana-champu','Ананда-вриндавана-чампу','Ānanda-vṛndāvana-campū','Поэтический свод игр Кришны во Вриндаване.','Кави Карнапура','kavi-karnapura','acharya',0,0,'ananda champu Карнапура Ананда-вриндавана-чампу',52),
('chaitanya-chandrodaya-nataka','Чайтанья-чандродая-натака','Caitanya-candrodaya-nāṭaka','Драма о явлении и играх Шри Чайтаньи.','Кави Карнапура','kavi-karnapura','acharya',0,0,'chandrodaya драма Карнапура Чайтанья-чандродая-натака',53),
('alankara-kaustubha','Аланкара-каустубха','Alaṅkāra-kaustubha','Трактат по санскритской поэтике и риторике.','Кави Карнапура','kavi-karnapura','acharya',0,0,'alankara поэтика Аланкара-каустубха',54),
('chaitanya-chandramrita','Чайтанья-чандрамрита','Caitanya-candrāmṛta','Сто строф во славу Шри Чайтаньи и Его милости.','Прабодхананда Сарасвати','prabodhananda-saraswati-thakur','acharya',0,0,'chandramrita Прабодхананда Чайтанья-чандрамрита',55),
('radha-rasa-sudha-nidhi','Радха-раса-судха-нидхи','Rādhā-rasa-sudhā-nidhi','Молитвы, прославляющие Шримати Радхарани.','Прабодхананда Сарасвати','prabodhananda-saraswati-thakur','acharya',0,0,'sudha nidhi Радха Радха-раса-судха-нидхи',56),
('vrindavana-mahimamrita','Вриндавана-махимамрита','Vṛndāvana-mahimāmṛta','Поэма о величии Шри Вриндавана-дхамы.','Прабодхананда Сарасвати','prabodhananda-saraswati-thakur','acharya',0,0,'mahima Вриндаван Вриндавана-махимамрита',57),
('gl','Говинда-лиламрита','Govinda-līlāmṛta','Поэтическое описание суточных игр (аштакалия-лила) Радхи-Кришны.','Кришнадас Кавираджа','krishnadasa-kaviraja','acharya',1,0,'lilamrita ashtakaliya Говинда-лиламрита govinda',58),
('madhurya-kadambini','Мадхурья-кадамбини','Mādhurya-kādambinī','Трактат о ступенях развития бхакти — от веры до премы.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'kadambini ступени бхакти Мадхурья-кадамбини',59),
('bhakti-rasamrita-sindhu-bindu','Бхакти-расамрита-синдху-бинду','Bhakti-rasāmṛta-sindhu-bindu','Краткое изложение «Бхакти-расамрита-синдху» Рупы.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'bindu синдху Бхакти-расамрита-синдху-бинду',60),
('sarartha-darshini','Сарартха-даршини','Sārārtha-darśinī','Комментарий к «Шримад-Бхагаватам».','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'sarartha комментарий Сарартха-даршини',61),
('krishna-bhavanamrita','Кришна-бхаванамрита','Kṛṣṇa-bhāvanāmṛta','Поэма о медитации на суточные игры Кришны.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'bhavanamrita Кришна-бхаванамрита',62),
('gurv-ashtaka','Гурв-аштака','Gurv-aṣṭaka','Восемь молитв духовному учителю.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'gurvashtaka гуру молитвы Гурв-аштака',63),
('govinda-bhashya','Говинда-бхашья','Govinda-bhāṣya','Гаудия-комментарий к «Веданта-сутре».','Баладева Видьябхушана','baladeva-vidyabhushana','acharya',0,0,'govinda bhashya Веданта Говинда-бхашья',64),
('prameya-ratnavali','Прамея-ратнавали','Prameya-ratnāvalī','Девять основных истин (прамей) гаудия-вайшнавизма.','Баладева Видьябхушана','baladeva-vidyabhushana','acharya',0,0,'prameya девять истин Прамея-ратнавали',65),
('gita-bhushana','Гита-бхушана','Gītā-bhūṣaṇa','Комментарий к «Бхагавад-гите».','Баладева Видьябхушана','baladeva-vidyabhushana','acharya',0,0,'gita bhushana Гита-бхушана',66),
('prarthana','Прартхана','Prārthanā','Молитвенные песни на бенгали о жажде служения.','Нароттама дас Тхакур','narottama-dasa-thakura','acharya',0,0,'prarthana песни Нароттама Прартхана',67),
('prema-bhakti-chandrika','Према-бхакти-чандрика','Prema-bhakti-candrikā','Песни о пути преданности и преме.','Нароттама дас Тхакур','narottama-dasa-thakura','acharya',0,0,'chandrika Нароттама Према-бхакти-чандрика',68),
('jaiva-dharma','Джайва-дхарма','Jaiva-dharma','Философский роман о вечной природе и пути души.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'jaiva роман Бхактивинода Джайва-дхарма',69),
('harinama-chintamani','Харинама-чинтамани','Harināma-cintāmaṇi','Наука святого имени и десять оскорблений.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'harinama имя Харинама-чинтамани',70),
('bhajana-rahasya','Бхаджана-рахасья','Bhajana-rahasya','Тайна бхаджаны по восьми строфам Шикшаштаки.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'bhajana rahasya Бхаджана-рахасья',71),
('sharanagati','Шаранагати','Śaraṇāgati','Песни о предании себя Господу (шесть видов шаранагати).','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'sharanagati песни предание Шаранагати',72),
('gitavali','Гитавали','Gītāvalī','Сборник бхаджанов и киртанов Бхактивиноды.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'gitavali песни Гитавали',73),
('kalyana-kalpataru','Кальяна-калпатару','Kalyāṇa-kalpataru','Сборник наставляющих и молитвенных песен.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'kalyana песни Кальяна-калпатару',74),
('navadvipa-dhama-mahatmya','Навадвипа-дхама-махатмья','Navadvīpa-dhāma-māhātmya','Слава святой земли Навадвипы и её девяти островов.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',1,0,'navadvipa махатмья дхама Навадвипа-дхама-махатмья Navadwipa dham',75),
('chaitanya-shikshamrita','Чайтанья-шикшамрита','Caitanya-śikṣāmṛta','Нектар учений Шри Чайтаньи в систематическом изложении.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'shikshamrita учения Чайтанья-шикшамрита',76),
('krishna-samhita','Кришна-самхита','Kṛṣṇa-saṁhitā','Богословский труд о Кришне и хронологии Его явления.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'krishna samhita Кришна-самхита',77),
('brahmana-and-vaishnava','Брахман и вайшнав','Brāhmaṇa o Vaiṣṇava','Эссе о соотношении положения брахмана и вайшнава.','Бхактисиддханта Сарасвати','bhaktisiddhanta-sarasvati','acharya',0,0,'brahmana vaishnava Бхактисиддханта Брахман и вайшнав',78),
('laghu-bhagavatamrita','Лагху-Бхагаватамрита','Laghu-bhāgavatāmṛta','Краткий обзор воплощений Господа и Его энергий.','Рупа Госвами','rupa-goswami','acharya',0,0,'laghu Лагху-Бхагаватамрита',79),
('krama-sandarbha','Крама-сандарбха','Krama-sandarbha','Последовательный комментарий Дживы Госвами к «Шримад-Бхагаватам».','Джива Госвами','jiva-goswami','acharya',0,0,'krama Крама-сандарбха',80),
('vilapa-kusumanjali','Вилапа-кусуманджали','Vilāpa-kusumāñjali','Молитвенная поэма-плач о служении Шримати Радхарани.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'vilapa kusumanjali Вилапа-кусуманджали',81),
('dana-keli-chintamani','Дана-кели-чинтамани','Dāna-keli-cintāmaṇi','Поэма об игре дана-лилы у Говардхана.','Рагхунатха дас Госвами','raghunatha-das-goswami','acharya',0,0,'dana keli Дана-кели-чинтамани',82),
('raga-vartma-chandrika','Рага-вартма-чандрика','Rāga-vartma-candrikā','Руководство по пути спонтанной преданности (рага-марга).','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'raga vartma Рага-вартма-чандрика',83),
('camatkara-candrika','Чаматкара-чандрика','Camatkāra-candrikā','Поэтическое описание сокровенных игр Радхи и Кришны.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'camatkara Чаматкара-чандрика',84),
('sankalpa-kalpadruma','Санкалпа-калпадрума','Saṅkalpa-kalpadruma','Молитва о вступлении в вечное служение в суточных играх.','Вишванатха Чакраварти','vishvanatha-chakravarti','acharya',0,0,'sankalpa Санкалпа-калпадрума',85),
('siddhanta-ratna','Сиддханта-ратна','Siddhānta-ratna','Философский трактат в защиту гаудия-веданты.','Баладева Видьябхушана','baladeva-vidyabhushana','acharya',0,0,'siddhanta ratna Сиддханта-ратна',86),
('vedanta-syamantaka','Веданта-сьямантака','Vedānta-syamantaka','Краткое изложение гаудия-веданты.','Баладева Видьябхушана','baladeva-vidyabhushana','acharya',0,0,'syamantaka Веданта-сьямантака',87),
('shikshashtaka','Шикшаштака','Śikṣāṣṭaka','Восемь стихов-наставлений — единственное письменное наследие Шри Кришна Чайтаньи Махапрабху.','Шри Кришна Чайтанья Махапрабху','chaitanya','acharya',0,0,'shikshashtaka восемь Шикшаштака',88),
('shad-goswami-ashtaka','Шри Шад-Госвами-аштака','Ṣaḍ-gosvāmy-aṣṭaka','Восемь строф во славу шести Госвами Вриндавана.','Шринивас Ачарья','srinivasa-acharya','acharya',0,0,'shad goswami ashtaka Шри Шад-Госвами-аштака',89),
('tattva-viveka','Таттва-вивека','Tattva-viveka','Философский анализ истины (Шри Саччидананда).','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'tattva viveka Таттва-вивека',90),
('tattva-sutra','Таттва-сутра','Tattva-sūtra','Афоризмы об истинах гаудия-философии.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'tattva sutra Таттва-сутра',91),
('amnaya-sutra','Амная-сутра','Āmnāya-sūtra','Сжатое изложение вайшнавского учения в сутрах.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'amnaya Амная-сутра',92),
('datta-kaustubha','Датта-каустубха','Datta-kaustubha','Сборник философских стихов Бхактивиноды.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'datta kaustubha Датта-каустубха',93),
('gita-mala','Гита-мала','Gītā-mālā','Сборник песен о пути преданности.','Бхактивинода Тхакур','bhaktivinoda-thakura','acharya',0,0,'gitamala песни Гита-мала',94),
('gita-govinda','Гита-Говинда','Gīta-govinda','Поэма о любви Радхи и Кришны.','Джаядева Госвами','jayadeva-gosvami','acharya',0,0,'gita govinda Джаядева Гита-Говинда',95),
('krishna-karnamrita','Кришна-карнамрита','Kṛṣṇa-karṇāmṛta','Нектар для слуха — молитвы во славу красоты Кришны.','Билвамангала Тхакур','bilvamangala','acharya',0,0,'karnamrita Лила-шука Кришна-карнамрита',96),
('govinda-damodara-stotra','Говинда-Дамодара-стотра','Govinda-dāmodara-stotra','Молитва, без устали призывающая имена Говинды и Дамодары.','Билвамангала Тхакур','bilvamangala','acharya',0,0,'govinda damodara Говинда-Дамодара-стотра',97),
('narada-bhakti-sutra','Нарада-бхакти-сутра','Nārada-bhakti-sūtra','Афоризмы о природе чистой преданности.','Нарада Муни','narada','acharya',0,0,'narada bhakti sutra Нарада-бхакти-сутра',98),
('shandilya-bhakti-sutra','Шандилья-бхакти-сутра','Śāṇḍilya-bhakti-sūtra','Афоризмы о науке преданного служения.','Шандилья Муни','shandilya-muni','acharya',0,0,'shandilya bhakti sutra Шандилья-бхакти-сутра',99),
('stotra-ratna','Стотра-ратна','Stotra-ratna','Драгоценность молитв Господу Нараяне.','Ямуначарья','yamunacharya','acharya',0,0,'stotra ratna Алавандар Стотра-ратна',100),
('damodarashtaka','Дамодараштака','Dāmodarāṣṭaka','Восемь молитв Господу Дамодаре, поются в месяц Картика.','Сатьяврата Муни','satyavrata-muni','acharya',0,0,'damodarashtaka Картика Дамодараштака',101),
('garga-samhita','Гарга-самхита','Garga-saṁhitā','Пуранический свод игр Кришны во Врадже.','Гарга Муни','garga-muni','acharya',0,0,'garga samhita Гарга-самхита',102),
('sri-bhashya','Шри-бхашья','Śrī-bhāṣya','Комментарий Рамануджи к «Веданта-сутре» (вишишта-адвайта).','Рамануджачарья','ramanujacharya','acharya',0,0,'sri bhashya Шри-бхашья',103),
('vedartha-sangraha','Ведартха-санграха','Vedārtha-saṅgraha','Изложение Рамануджей смысла Вед.','Рамануджачарья','ramanujacharya','acharya',0,0,'vedartha Ведартха-санграха',104),
('gita-bhashya-ramanuja','Гита-бхашья (Рамануджа)','Gītā-bhāṣya','Комментарий Рамануджи к «Бхагавад-гите».','Рамануджачарья','ramanujacharya','acharya',0,0,'gita bhashya ramanuja Гита-бхашья (Рамануджа)',105),
('saranagati-gadya','Шаранагати-гадья','Śaraṇāgati-gadya','Молитва Рамануджи о предании у стоп Господа.','Рамануджачарья','ramanujacharya','acharya',0,0,'saranagati gadya Шаранагати-гадья',106),
('rahasya-traya-sara','Рахасья-трая-сара','Rahasya-traya-sāra','Изложение трёх сокровенных мантр Шри-вайшнавов.','Веданта Дешика','vedanta-desika','acharya',0,0,'rahasya traya Рахасья-трая-сара',107),
('anubhashya','Анубхашья','Aṇu-bhāṣya','Комментарий Валлабхи к «Веданта-сутре» (шуддха-адвайта).','Валлабхачарья','vallabhacharya','acharya',0,0,'anubhashya Анубхашья',108),
('subodhini','Субодхини','Subodhinī','Комментарий Валлабхи к «Шримад-Бхагаватам».','Валлабхачарья','vallabhacharya','acharya',0,0,'subodhini Субодхини',109),
('shodasha-grantha','Шодаша-грантха','Ṣoḍaśa-grantha','Шестнадцать кратких трактатов о пути пушти-бхакти.','Валлабхачарья','vallabhacharya','acharya',0,0,'shodasha Шодаша-грантха',110),
('vedanta-parijata-saurabha','Веданта-париджата-саурабха','Vedānta-pārijāta-saurabha','Комментарий Нимбарки к «Веданта-сутре».','Нимбаркачарья','nimbarkacharya','acharya',0,0,'parijata saurabha Веданта-париджата-саурабха',111),
('dasha-shloki','Даша-шлоки','Daśa-ślokī','Десять стихов, излагающих суть учения Нимбарки.','Нимбаркачарья','nimbarkacharya','acharya',0,0,'dasha shloki Даша-шлоки',112),
('gita-bhashya-madhva','Гита-бхашья (Мадхва)','Gītā-bhāṣya','Комментарий Мадхвы к «Бхагавад-гите».','Мадхвачарья','madhva','acharya',0,0,'gita bhashya madhva Гита-бхашья (Мадхва)',113),
('anuvyakhyana','Анувьякхьяна','Anuvyākhyāna','Главный труд Мадхвы по «Веданта-сутре».','Мадхвачарья','madhva','acharya',0,0,'anuvyakhyana Анувьякхьяна',114),
('manah-siksa','Манах-шикша','Manaḥ-śikṣā','Наставления собственному уму','Шрила Рагхунатха дас Госвами',NULL,'acharya',1,1,'Manah-siksa Manah Shiksa Манах-шикша Рагхунатха Raghunatha dasa Goswami',115),
('siksastaka','Шри Шикшаштака','Śrī Śikṣāṣṭaka','Восемь наставлений Господа Чайтаньи','Шри Чайтанья Махапрабху',NULL,'acharya',1,1,'Sikshashtaka Siksastaka Шикшаштака Чайтанья Caitanya Chaitanya vivriti виврити',116),
('bhakti-tattva-viveka','Бхакти-таттва-вивека','Bhakti-tattva-viveka','Различение истины о преданности','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Bhakti-tattva-viveka Бхакти-таттва-вивека Бхактивинода Bhaktivinoda Thakura',117),
('mukunda-mala-stotra','Мукунда-мала-стотра','Mukunda-mālā-stotra','Молитвенное ожерелье Мукунде','Махараджа Кулашекхара',NULL,'acharya',1,1,'Mukunda-mala-stotra Мукунда-мала Кулашекхара Kulasekhara Kulashekhara',118),
('sanmodana-bhashya','Санмодана-бхашья','Sanmodana-bhāṣya','Комментарий к «Шикшаштаке»','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Sanmodana-bhashya Санмодана-бхашья Бхактивинода Siksastaka Шикшаштака',119),
('bhaktyaloka','Бхактьялока','Bhaktyāloka','Свет преданности','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Bhaktyaloka Бхактьялока Бхактивинода anarthas анартхи',120),
('prema-pradipa','Према-прадипа','Prema-pradīpa','Светильник чистой любви','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Prema-pradipa Према-прадипа Бхактивинода',121),
('harinama-cintamani','Харинама-чинтамани','Harināma-cintāmaṇi','Философский камень святого имени','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Harinama-cintamani Харинама-чинтамани Бхактивинода holy name namaparadha оскорбления',122),
('caitanya-siksamrta','Чайтанья-шикшамрита','Caitanya-śikṣāmṛta','Нектар учения Господа Чайтаньи','Шрила Бхактивинода Тхакур',NULL,'acharya',1,1,'Caitanya-siksamrita Чайтанья-шикшамрита Бхактивинода Chaitanya',123),
('jagannatha-vallabha-nataka','Джаганнатха-валлабха-натака','Jagannātha-vallabha-nāṭaka','Драма о Возлюбленном Джаганнатхи','Шри Рамананда Рай',NULL,'acharya',1,1,'Jagannatha-vallabha-nataka Джаганнатха-валлабха Рамананда Ramananda Raya',124),
('sri-namamrita','Шри Намамрита','Śrī Nāmāmṛta','Нектар святого имени','Его Божественная Милость А. Ч. Бхактиведанта Свами Шрила Прабхупада','prabhupada','prabhupada',1,1,'Sri Namamrita Namamrta Шри Намамрита святое имя Prabhupada Bhaktivedanta',125),
('ray-of-vishnu','Луч Вишну','A Ray of Viṣṇu','Жизнь Бхактисиддханты Сарасвати','Рупа-виласа дас',NULL,'acharya',1,1,'Ray of Vishnu Луч Вишну Бхактисиддханта Bhaktisiddhanta Sarasvati',126),
('uroki-lyubvi','Уроки любви',NULL,'Истории из жизни Шрилы Прабхупады','Бхакти Вигьяна Госвами',NULL,'guru-iskcon',1,0,'Уроки любви Бхакти Вигьяна Госвами Bhakti Vijnana Goswami',127),
('seventh-goswami','Седьмой Госвами','The Seventh Goswāmī','Жизнь Бхактивиноды Тхакура','Рупа-виласа дас',NULL,'acharya',1,0,'Seventh Goswami Седьмой Госвами Бхактивинода Bhaktivinoda biography',128),
('the-beggar','Нищий','The Beggar','Медитации и молитвы','Бхакти Тиртха Свами',NULL,'guru-iskcon',1,0,'The Beggar Нищий Бхакти Тиртха Свами Bhakti Tirtha Swami meditations',129),
('vrindavane-bhajana','Вриндаване бхаджана','Vṛndāvana-bhajana','Поэма с комментариями Джаяпатаки Свами','Шрила Прабхупада','prabhupada','prabhupada',1,1,'Vrindavana bhajana Вриндаване бхаджана Прабхупада Джаяпатака Jayapataka Swami',130);
